#!/bin/bash
Green="\e[92;1m"
RED="\033[1;31m"
YELLOW="\033[33m"
BLUE="\033[36m"
FONT="\033[0m"
GREENBG="\033[42;37m"
REDBG="\033[41;37m"
NC='\e[0m'
REPOS="https://raw.githubusercontent.com/Pemulaajiw/tunnel/main/"
ns_domain_cloudflare() 
DOMAIN=devstun.my.id
sub=$(</dev/urandom tr -dc a-z0-9 | head -c5)
dns=${sub}.devstun.my.id
CF_ID=cocresult1@gmail.com
CF_KEY=8b69a018ff18da71e5d8297e720e14cb38286
set -euo pipefail
IP=$(wget -qO- icanhazip.com);
echo "Updating DNS for ${dns}..."
	ZONE=$(
		curl -sLX GET "https://api.cloudflare.com/client/v4/zones?name=${DOMAIN}&status=active" \
		-H "X-Auth-Email: ${CF_ID}" \
		-H "X-Auth-Key: ${CF_KEY}" \
		-H "Content-Type: application/json" | jq -r .result[0].id
	)

	RECORD=$(
		curl -sLX GET "https://api.cloudflare.com/client/v4/zones/${ZONE}/dns_records?name=${NS_DOMAIN}" \
		-H "X-Auth-Email: ${CF_ID}" \
		-H "X-Auth-Key: ${CF_KEY}" \
		-H "Content-Type: application/json" | jq -r .result[0].id
	)

	if [[ "${#RECORD}" -le 10 ]]; then
		RECORD=$(
			curl -sLX POST "https://api.cloudflare.com/client/v4/zones/${ZONE}/dns_records" \
			-H "X-Auth-Email: ${CF_ID}" \
			-H "X-Auth-Key: ${CF_KEY}" \
			-H "Content-Type: application/json" \
			--data '{"type":"NS","name":"'${NS_DOMAIN}'","content":"'${DOMAIN_PATH}'","proxied":false}' | jq -r .result.id
		)
	fi

	RESULT=$(
		curl -sLX PUT "https://api.cloudflare.com/client/v4/zones/${ZONE}/dns_records/${RECORD}" \
		-H "X-Auth-Email: ${CF_ID}" \
		-H "X-Auth-Key: ${CF_KEY}" \
		-H "Content-Type: application/json" \
		--data '{"type":"NS","name":"'${NS_DOMAIN}'","content":"'${DOMAIN_PATH}'","proxied":false}'
	)
	fi
}
setup_dnstt() {
	cd
	mkdir -p /etc/slowdns
	cd /etc/slowdns
	wget -O dnstt-server "${REPOS}original/dnstt-server" >/dev/null 2>&1 #arahkan ke file di gh Wajib!!
	chmod +x dnstt-server >/dev/null 2>&1
	wget -O dnstt-client "${REPOS}original/dnstt-client" >/dev/null 2>&1 #arahkan ke file di gh Wajib!!
	chmod +x dnstt-client >/dev/null 2>&1
	./dnstt-server -gen-key -privkey-file server.key -pubkey-file server.pub
	chmod +x *
	cd
	wget -O /etc/systemd/system/client.service "${REPOS}original/client" >/dev/null 2>&1 #arahkan ke file di gh Wajib!!
	wget -O /etc/systemd/system/server.service "${REPOS}original/server" >/dev/null 2>&1 #arahkan ke file di gh Wajib!!
	sed -i "s/xxxx/$NS_DOMAIN/g" /etc/systemd/system/client.service 
	sed -i "s/xxxx/$NS_DOMAIN/g" /etc/systemd/system/server.service 
	systemctl daemon-reload
	systemctl restart server
	systemctl restart client
	systemctl enable server
	systemctl enable client
}
print_install() {
echo -e "${BLUE} =============================== ${FONT}"
echo -e "${YELLOW} # $1 ${FONT}"
echo -e "${BLUE} =============================== ${FONT}"
sleep 1
}
print_success() {
if [[ 0 -eq $? ]]; then
echo -e "${BLUE} =============================== ${FONT}"
echo -e "${Green} # $1 berhasil dipasang"
echo -e "${BLUE} =============================== ${FONT}"
sleep 2
fi
}
setup(){
echo ""
echo ""
echo -e "   ${BLUE}_______________________________$NC"
echo -e "   \e[1;32m    WELCOME TO SLOWDNS SETUP $NC"
echo -e "   ${BLUE}_______________________________$NC"
echo ""
echo "    Menyiapan Pemasangan Slowdns dalam 2 detik !"
sleep 2
clear
ns_domain_cloudflare
setup_dnstt
echo ""
rm -rf nameserver
clear
print_success "SETUP SLOWDNS YOUR SERVER"
sleep 2
menu
}
setup
